### ISSUE TITLE
add callback support

### ISSUE THREAD

**Issue by branciard** [iExecBlockchainComputing/xtremweb-hep#94]
In case of callback param valorized on workorder. 
After the finalizeWork call on workerpoool, a best effort callback must be done by the scheduler. 
See test exemple here : https://github.com/iExecBlockchainComputing/PoCo/blob/master/test/byFunctions/Marketplace/workOrderCallback.js#L493

**Comment by branciard** [comment]
slackuser :
Et concernant les issue 94 et 93 pour le bénéficiaire d'une exécution, où est ce que je peux voir leur avancement ? Je ne les ai pas trouvé sur github
ah si c'est bon
elles sont dans xtremweb-hep
Tu as une estimation du délai de leur résolution ? 1 semaine, 1 mois ? plus ?
Que je sache sur quelle partie de mon application travailler en priorité

francois [3:42 PM]
Je demande a mes collegues.

slackuser [3:43 PM]
Merci :slightly_smiling_face:

slackuser [4:52 PM]
Tu as pu avoir l'info ?

slackuser [3:37 PM]
Bonjour Francois
Tu as pu avoir la réponse concernant ma question de la dernière fois ?
Et j'avais une autre question : comment je peux faire pour renvoyer une chaine de caractères au smart contract ?
Je pense que c'est le contenu du stdout, c'est cela ?

francois [3:42 PM]
Bonjour , oui ce sera stdout.

**Comment by Andy92Pac** [comment]
There is a need for the possibility to select the content that the dockerized application return to the smart contract. As talked with a dev, a file named callback.log for example could hold this content and help to transfer it to the smart contract.
